### ISSUE TITLE
Sample code for running pipeline

### ISSUE THREAD

**Issue by Timoeller** [pjox/goclassy#1]
Hey folks, great work on making nlp data available for other languages, also in the Oscar project.

Unfortunately most language models need successive sentences for training and Oscar is shuffled.

I am a complete go noob, so could you include some sample code (cmd line calls to go scripts?) for making your pipeline run on common crawl data? That would be highly appreciated.
Thanks

**Comment by pjox** [comment]
Hello and thank you for your question. We are actually planning on refactoring most of the code, there are a lots of improvements to be made and lots of bugs to correct. If you really want to run it, you just need to compile it with go build and then run it like

`./goclassy /path/to/directory/where/the/gzip/wet/files/are/located`

It also needs a compiled version of fasttext in an adjacent directory called `fasttext`.

In the mean time though, we do have unshuffled versions of every language (without the metadata) and we can distribute them on a request basis, provided you're going to use it for research. So let me know if you're interested.

**Comment by Timoeller** [comment]
Hey @pjox Thanks for the fast reply. 

I sent you a personal mail coming from my work mail timo.moeller@deepset.ai to your inria address.
It possibly went into your spam folder since I included a lot of links...

**Comment by kalyangvs** [comment]
Hi as per this, 
```Note: For the moment the downloader part of the pipeline is not available as it is still experimental, it will be open sourced in a future release.```
Can you please point me to the deduplication  tool  `runiq` part of the pipeline.

**Comment by pjox** [comment]
Hello,

Sorry for the delay in answering, here is the link to `runiq`: https://github.com/whitfin/runiq

**Comment by SeanDunford** [comment]
@pjox - Will you be continuing work on this project?

**Comment by pjox** [comment]
@SeanDunford Yes! I'm actually working right now on a second version of OSCAR and I'll be refactoring all the goclassy code, I'll finally add the downloader section, and I'll add tools to extract metadata and generate .json documents.

Please note that for the moment this is a one person project, so it might be slow at first, but I'm actually trying to get more people involved in both goclassy and OSCAR.

**Comment by SeanDunford** [comment]
Beautiful. 

Im very interested in this project and hope to use it as the basis for an idea i have in mind. 

Currently im only looking to do link traversal in common crawl. Classification is something that will be more interesting to me in the future. 

I was having trouble ubderstanding how to get go classy up on my local machine. 

Im new to go but familiar with scraping and just general backend development. 

Do you have work specced out in tickets somewhere? Not sure how much time i have but happy to help on weekends if i see something thats within my skillset.

**Comment by pjox** [comment]
@SeanDunford Amazing! No, I don't have tickets yet, just a set of goals. I've been busy lately with an article we published about training language models with OSCAR, but as soon as that's finished  I'll stark working on a clear roadmap.

More people will also be joining the project over the summer, so I expect to have a clearer workflow soon. Thank you so much for offering your help, I greatly appreciate it! Let me just organize de project a little bit so that we can work more effectively.

As for the documentation, I'll be working on that with an intern soon. We're going to comment all the code and create a website for the documentation as we refactor the code.

Thank you once again!

**Comment by SeanDunford** [comment]
Sick.
