### ISSUE TITLE
Deduplication

### ISSUE THREAD

**Issue by Tixierae** [pjox/goclassy#2]
Hi, quick question about the OSCAR creation pipeline as described in the original paper.

The paper says that after language tagging, deduplication was performed with runiq separately on the 160 per-language WET files. Could you please explain what was the motivation for using deduplication?

Obviously, the uniqueness of the webpages needs to be ensured, either at the crawler level or during post-processing. That is, each text file should originate from a unique webpage, there should not be duplicates.

But, as far as the lines, the probability that two lines from two different pages are exactly the same is very low, except for very short/junk lines (e.g., ‘table of contents’, ‘welcome to my blog’, etc.). Isn't it?
And, even if two longer lines were exactly the same, would that be a problem? When training a language model on an entire Wikipedia dump, one usually does not check for duplicate sentences.

I'm probably missing something here. Could you please clarify the reasons why you used deduplication?

Thanks!

**Comment by Tixierae** [comment]
Copying the answer obtained via email correspondence from Pedro J. Ortiz and closing.

> This deduplication step is precisely done in order to remove the very short/junk lines (e.g., ‘table of contents’, ‘welcome to my blog’, etc.). Removing this line actually makes a huge difference, as performing this deduplication step removes almost half of the data in the corpus.

> If you want to know more about it, I recommend the discussion in Facebook’s paper "Learning Word Vectors for 157 Languages” (https://arxiv.org/pdf/1802.06893.pdf) section 2.3. They also cite other sources of people which had exactly the same experience with this striking reduction in data just by deduplication.

**Comment by pjox** [comment]
@Tixierae Thanks so much for posting the answer here, I had completely forgotten about it!
